os: linux
dist: bionic
services:
  - xvfb
language: python
cache: bundler

addons:
  apt:
    packages:
      - libenchant-dev
      - python3-pyqt5
      - python3-pyqt5.qtsvg

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
# - pip install pytest-faulthandler
  - pip install PyVirtualDisplay
  - pip install pytest-xvfb
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install codecov

stages:
  - name: Initial
  - name: Full

jobs:
  include:
    - stage: Initial
      python:
        - 3.8
      script:
        - python -m pytest --cov=nw -m "project|core|gui" -v
      after_success:
        - codecov
      after_failure:
        - cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes

    - stage: Full
      python:
        - 3.6
        - 3.7
      script:
        - python -m pytest --cov=nw -m "project|core|gui" -v
