name: Build

on:
  push:
    branches:
      - i18n/*

jobs:
  buildI18n:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64
      - name: Install Packages (apt)
        run: |
          sudo apt update
          sudo apt install qttools5-dev-tools
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build Assets
        run: python pkgutils.py qtlrelease
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nw-i18n
          path: |
            novelwriter/assets/i18n/*.qm
          if-no-files-found: error
          retention-days: 7
