name: LockThreads

on:
  schedule:
    - cron: "40 * * * *"

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: 120
          # issue-comment: >
          #   This issue has been automatically locked since there has not been
          #   any recent activity after it was closed. Please open a new issue
          #   for related bugs or feature requests.
          issue-lock-reason: "resolved"
          pr-inactive-days: 120
          # pr-comment: >
          #   This pull request thread has been automatically locked since there
          #   has not been any recent activity after it was closed. Please open
          #   an issue for any related bugs or feature requests.
          pr-lock-reason: "resolved"
          process-only: "issue, pr"
          log-output: true
